### ISSUE TITLE
LDAP connection problem

### ISSUE THREAD

**Issue by kuzaxak** [martinpaljak/esteid-sk#2]
Hi, I'm trying to use your cli tool. But I can run it because of LDAP connection problem:

From my investigation it happens because version of this package it too old. And at the same time I can't find new versions in maven search. 

Could you please publish latest version with [fix][1] to maven registry? 

```
Exception in thread "main" javax.naming.CommunicationException: ldap.sk.ee:389 [Root exception is java.net.ConnectException: Operation timed out]
	at java.naming/com.sun.jndi.ldap.Connection.<init>(Connection.java:237)
	at java.naming/com.sun.jndi.ldap.LdapClient.<init>(LdapClient.java:137)
	at java.naming/com.sun.jndi.ldap.LdapClient.getInstance(LdapClient.java:1610)
	at java.naming/com.sun.jndi.ldap.LdapCtx.connect(LdapCtx.java:2751)
	at java.naming/com.sun.jndi.ldap.LdapCtx.<init>(LdapCtx.java:319)
	at java.naming/com.sun.jndi.ldap.LdapCtxFactory.getLdapCtxFromUrl(LdapCtxFactory.java:225)
	at java.naming/com.sun.jndi.ldap.LdapCtxFactory.getUsingURL(LdapCtxFactory.java:189)
	at java.naming/com.sun.jndi.ldap.LdapCtxFactory.getUsingURLs(LdapCtxFactory.java:243)
	at java.naming/com.sun.jndi.ldap.LdapCtxFactory.getLdapCtxInstance(LdapCtxFactory.java:154)
	at java.naming/com.sun.jndi.ldap.LdapCtxFactory.getInitialContext(LdapCtxFactory.java:84)
	at java.naming/javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:730)
	at java.naming/javax.naming.InitialContext.getDefaultInitCtx(InitialContext.java:305)
	at java.naming/javax.naming.InitialContext.init(InitialContext.java:236)
	at java.naming/javax.naming.ldap.InitialLdapContext.<init>(InitialLdapContext.java:154)
	at org.esteid.sk.LDAP.query(LDAP.java:56)
	at org.esteid.sk.LDAP.fetch(LDAP.java:84)
	at org.cdoc4j.cli.Tool.main(Tool.java:232)
Caused by: java.net.ConnectException: Operation timed out
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:503)
	at java.base/sun.nio.ch.Net.connect(Net.java:492)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:333)
	at java.base/java.net.Socket.connect(Socket.java:648)
	at java.base/java.net.Socket.connect(Socket.java:597)
	at java.base/java.net.Socket.<init>(Socket.java:520)
	at java.base/java.net.Socket.<init>(Socket.java:294)
	at java.naming/com.sun.jndi.ldap.Connection.createSocket(Connection.java:330)
	at java.naming/com.sun.jndi.ldap.Connection.<init>(Connection.java:216)
	... 16 more
```

[1]: https://github.com/martinpaljak/esteid-sk/blob/master/src/main/java/org/esteid/sk/LDAP.java#L41

**Comment by kuzaxak** [comment]
Okay, I found that you are using private repo. 

https://javacard.pro/maven/com/github/martinpaljak/esteid-sk/20.06.04/

Will try to enable it in maven build in cli tool.
